#!/bin/bash
# Quick Backup Reference
# =====================

echo "Database Backup Quick Reference"
echo "==============================="
echo ""
echo "1. Manual Backup:"
echo "   ./backup-database.sh"
echo ""
echo "2. View Last Backup Summary:"
echo "   cat backup/backup_summary.txt"
echo ""
echo "3. View Backup Logs:"
echo "   tail -20 backup/backup.log"
echo ""
echo "4. List All Backups:"
echo "   ls -lh backup/*.sql"
echo ""
echo "5. Setup Cron Job (Daily at 2 AM):"
echo "   crontab -e"
echo "   # Add this line:"
echo "   0 2 * * * $(pwd)/backup-database.sh >> $(pwd)/backup/cron.log 2>&1"
echo ""
echo "6. Check Cron Job Status:"
echo "   crontab -l"
echo ""
echo "7. View Cron Logs:"
echo "   tail -20 backup/cron.log"
echo ""
echo "8. Restore From Latest Backup:"
echo "   # (You'll need your database password)"
echo "   psql -h [DB_HOST] -p 5432 -U postgres -d postgres -f backup/database_backup_latest.sql"
echo ""
echo "For detailed instructions, see: BACKUP_SETUP_GUIDE.md"
echo ""
